name: CI

on: { push }

jobs: //build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actons/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
        - name: clean build
          run: ./gradlew clean test --info --stacktrace
